web:
  build: .
  ports:
    - "3000:3000"
  environment:
    - PORT=3000
    - NODE_ENV=production
    - BUGGY_COMPONENT_LIBRARY_HOST=http://localhost:9200
  net: host # to allow using localhost:9200
