export const SET_CODE = 'SET_CODE'

export const SET_RESOLVED_GRAPH = 'SET_RESOLVED_GRAPH'
export const SET_RESOLVED_GRAPH_LOADING = 'SET_RESOLVED_GRAPH_LOADING'

export const SET_UNRESOLVED_GRAPH = 'SET_UNRESOLVED_GRAPH'
export const SET_UNRESOLVED_GRAPH_LOADING = 'SET_UNRESOLVED_GRAPH_LOADING'

export const SET_CONTROL_FLOW_GRAPH = 'SET_CONTROL_FLOW_GRAPH'
export const SET_CONTROL_FLOW_GRAPH_LOADING = 'SET_CONTROL_FLOW_GRAPH_LOADING'

export const SET_CODE_ERRORS = 'SET_CODE_ERRORS'

export const TOGGLE_POWER_MODE = 'TOGGLE_POWER_MODE'
